version: '3'

networks:
  django_drf_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    networks:
      - django_drf_network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: postgres
    networks:
      - django_drf_network
    restart: on-failure
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER' ]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    tty: true
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    networks:
      - django_drf_network
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  celery:
    build: .
    networks:
      - django_drf_network
    tty: true
    command: celery -A config worker -l INFO
    restart: on-failure
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started

  celery_beat:
    build: .
    networks:
      - django_drf_network
    tty: true
    command: [ "sh", "-c", "celery -A config beat -l INFO && celery -A config -l info -P gevent" ]
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started

volumes:
  pg_data: